# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 12f13904ad8a541a0f99ac492a4ae19ce84ac161f5c0ed829a52139f7a5a4bd03e2b4507850fee6b4deec185e7eb114228538c1b6b1d7462770c3e4655c7a30c

test:
  secret_key_base: 7d8677369ede0efbfbbd959e44c0c9b93d1b4306d1062960f35ac112a1b1730acf52c8e09acc6bdac17d53c22539799e7dd258ea61cd090277316e54a96318bf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
